In [4]:
import pandas as pd

df = pd.read_csv("13adult.csv")

In [5]:
df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48842 non-null  int64
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64
 11  capital-loss     48842 non-null  int64
 12  hours-per-week   48842 non-null  int64
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

In [7]:
df.groupby("education")['age'].mean()

education
10th            37.902808
11th            32.141832
12th            32.235921
1st-4th         46.639676
5th-6th         43.585462
7th-8th         49.525654
9th             40.902116
Assoc-acdm      37.777014
Assoc-voc       38.651140
Bachelors       38.896324
Doctorate       47.530303
HS-grad         39.073809
Masters         44.006775
Preschool       42.204819
Prof-school     45.152278
Some-college    35.677055
Name: age, dtype: float64

In [8]:
df.groupby("education")['age'].median()

education
10th            35.0
11th            28.0
12th            28.0
1st-4th         46.0
5th-6th         43.0
7th-8th         51.0
9th             39.0
Assoc-acdm      37.0
Assoc-voc       37.0
Bachelors       37.0
Doctorate       47.0
HS-grad         37.0
Masters         44.0
Preschool       41.0
Prof-school     43.0
Some-college    34.0
Name: age, dtype: float64

In [9]:
df.groupby("education")['age'].std()

education
10th            16.905226
11th            15.245833
12th            14.692293
1st-4th         15.172575
5th-6th         15.536060
7th-8th         16.290025
9th             15.830591
Assoc-acdm      11.362256
Assoc-voc       11.651413
Bachelors       11.894758
Doctorate       11.469584
HS-grad         13.655181
Masters         11.036663
Preschool       15.389067
Prof-school     12.186115
Some-college    13.497178
Name: age, dtype: float64

In [10]:
df.groupby("education")['age'].describe()

                count       mean        std   min   25%   50%   75%   max
education
10th           1389.0  37.902808  16.905226  17.0  22.0  35.0  52.0  90.0
11th           1812.0  32.141832  15.245833  17.0  18.0  28.0  42.0  90.0
12th            657.0  32.235921  14.692293  17.0  19.0  28.0  42.0  81.0
1st-4th         247.0  46.639676  15.172575  19.0  34.5  46.0  57.5  90.0
5th-6th         509.0  43.585462  15.536060  17.0  30.0  43.0  55.0  84.0
7th-8th         955.0  49.525654  16.290025  17.0  36.0  51.0  62.0  90.0
9th             756.0  40.902116  15.830591  17.0  28.0  39.0  54.0  90.0
Assoc-acdm     1601.0  37.777014  11.362256  19.0  29.0  37.0  45.0  90.0
Assoc-voc      2061.0  38.651140  11.651413  19.0  30.0  37.0  46.0  84.0
Bachelors      8025.0  38.896324  11.894758  19.0  29.0  37.0  46.0  90.0
Doctorate       594.0  47.530303  11.469584  24.0  39.0  47.0  55.0  80.0
HS-grad       15784.0  39.073809  13.655181  17.0  28.0  37.0  49.0  90.0
Masters        2657.0  44.006775  11.036663  18.0  36.0  44.0  51.0  90.0
Preschool        83.0  42.204819  15.389067  19.0  30.0  41.0  53.5  77.0
Prof-school     834.0  45.152278  12.186115  25.0  37.0  43.0  52.0  90.0
Some-college  10878.0  35.677055  13.497178  17.0  23.0  34.0  45.0  90.0

In [11]:
list_data = df.groupby("education")["age"].mean().tolist()

In [12]:
print(list_data)

[37.90280777537797, 32.14183222958057, 32.23592085235921, 46.63967611336032, 43.585461689587426, 49.52565445026178, 40.902116402116405, 37.777014366021234, 38.65114022319263, 38.89632398753894, 47.53030303030303, 39.07380892042575, 44.00677455777193, 42.204819277108435, 45.15227817745804, 35.67705460562603]

# Iris Dataset

In [13]:
import pandas as pd
df = pd.read_csv("13Iris.csv")

In [14]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [16]:
df.drop('Id', axis=1)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [18]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'species'],
      dtype='object')

In [19]:
df['species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [20]:
df.groupby("species").describe()

                   Id                                                        \
                count   mean       std    min     25%    50%     75%    max
species
Iris-setosa      50.0   25.5  14.57738    1.0   13.25   25.5   37.75   50.0
Iris-versicolor  50.0   75.5  14.57738   51.0   63.25   75.5   87.75  100.0
Iris-virginica   50.0  125.5  14.57738  101.0  113.25  125.5  137.75  150.0

                SepalLengthCm         ... PetalLengthCm      PetalWidthCm  \
                        count   mean  ...           75%  max        count
species                               ...
Iris-setosa              50.0  5.006  ...         1.575  1.9         50.0
Iris-versicolor          50.0  5.936  ...         4.600  5.1         50.0
Iris-virginica           50.0  6.588  ...         5.875  6.9         50.0


                  mean       std  min  25%  50%  75%  max
species
Iris-setosa      0.244  0.107210  0.1  0.2  0.2  0.3  0.6
Iris-versicolor  1.326  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica   2.026  0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 40 columns]

In [21]:
setosa = df[(df['species'] == 'Iris-setosa')]

In [25]:
print("Mean of setosa : ", setosa.mean(numeric_only=True))
print("Median of setosa : ", setosa.median(numeric_only=True))
print("Standard Deviation of setosa : ", setosa.std(numeric_only=True))
print("Percentiles of setosa : ", setosa.quantile([0.25, 0.5, 0.75], numeric_only=True))

Mean of setosa :  Id               25.500
SepalLengthCm     5.006
SepalWidthCm      3.418
PetalLengthCm     1.464
PetalWidthCm      0.244
dtype: float64
Median of setosa :  Id               25.5
SepalLengthCm     5.0
SepalWidthCm      3.4
PetalLengthCm     1.5
PetalWidthCm      0.2
dtype: float64
Standard Deviation of setosa :  Id               14.577380
SepalLengthCm     0.352490
SepalWidthCm      0.381024
PetalLengthCm     0.173511
PetalWidthCm      0.107210
dtype: float64
Percentiles of setosa :           Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0.25  13.25            4.8         3.125          1.400           0.2
0.50  25.50            5.0         3.400          1.500           0.2
0.75  37.75            5.2         3.675          1.575           0.3

In [26]:
versicolor = df[(df['species'] == 'Iris-versicolor')]

print("Mean of versicolor: ", versicolor.mean(numeric_only=True))
print("Median of versicolor: ", versicolor.median(numeric_only=True))
print("Standard Deviation of versicolor: ", versicolor.std(numeric_only=True))
print("Percentiles of versicolor: ", versicolor.quantile([0.25, 0.5, 0.75], numeric_only=True))

Mean of versicolor:  Id               75.500
SepalLengthCm     5.936
SepalWidthCm      2.770
PetalLengthCm     4.260
PetalWidthCm      1.326
dtype: float64
Median of versicolor:  Id               75.50
SepalLengthCm     5.90
SepalWidthCm      2.80
PetalLengthCm     4.35
PetalWidthCm      1.30
dtype: float64
Standard Deviation of versicolor:  Id               14.577380
SepalLengthCm     0.516171
SepalWidthCm      0.313798
PetalLengthCm     0.469911
PetalWidthCm      0.197753
dtype: float64
Percentiles of versicolor:           Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0.25  63.25            5.6         2.525           4.00           1.2
0.50  75.50            5.9         2.800           4.35           1.3
0.75  87.75            6.3         3.000           4.60           1.5

In [27]:
virginica = df[(df['species'] == 'Iris-virginica')]

print("Mean of virginica: ", virginica.mean(numeric_only=True))
print("Median of virginica: ", virginica.median(numeric_only=True))
print("Standard Deviation of virginica: ", virginica.std(numeric_only=True))
print("Percentiles of virginica: ", virginica.quantile([0.25, 0.5, 0.75], numeric_only=True))

Mean of virginica:  Id               125.500
SepalLengthCm      6.588
SepalWidthCm       2.974
PetalLengthCm      5.552
PetalWidthCm       2.026
dtype: float64
Median of virginica:  Id               125.50
SepalLengthCm      6.50
SepalWidthCm       3.00
PetalLengthCm      5.55
PetalWidthCm       2.00
dtype: float64
Standard Deviation of virginica:  Id               14.577380
SepalLengthCm     0.635880
SepalWidthCm      0.322497
PetalLengthCm     0.551895
PetalWidthCm      0.274650
dtype: float64
Percentiles of virginica:            Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0.25  113.25          6.225         2.800          5.100           1.8
0.50  125.50          6.500         3.000          5.550           2.0
0.75  137.75          6.900         3.175          5.875           2.3