In [1]:
Data Wrangling, I 

Perform the following operations using Python on any open source dataset (e.g., data.csv) 
1. Import all the required Python Libraries. 
2. Locate an open source data from the web (e.g., https://www.kaggle.com). Provide a clear description of the data and its source (i.e., URL of the web site). 
3. Load the Dataset into pandas dataframe. 
4. Data Preprocessing: check for missing values in the data using pandas isnull(), describe() function to get some initial statistics. Provide variable descriptions. Types of variables etc. Check the dimensions of the data frame. 
5. Data Formatting and Data Normalization: Summarize the types of variables by checking the data types (i.e., character, numeric, integer, factor, and logical) of the variables in the data set. If variables are not in the correct data type, apply proper type conversions. 
6. Turn categorical variables into quantitative variables in Python. 
 
In addition to the codes and outputs, explain every operation that you do in the above steps and 
explain everything that you do to import/read/scrape the data set.

SyntaxError: invalid syntax (3519058326.py, line 1)

In [16]:
import pandas as pd
import numpy as np

In [18]:
df = pd.read_csv("Titanic.csv")
df.head()

,Name,PClass,Age,Sex,Survived
0,"Allen, Miss Elisabeth Walton",1st,29.00,female,1
1,"Allison, Miss Helen Loraine",1st,2.00,female,0
2,"Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0
4,"Allison, Master Hudson Trevor",1st,0.92,male,1

In [20]:
df.tail()

                        Name PClass   Age   Sex  Survived
1308      Zakarian, Mr Artun    3rd  27.0  male         0
1309  Zakarian, Mr Maprieder    3rd  26.0  male         0
1310        Zenni, Mr Philip    3rd  22.0  male         0
1311        Lievens, Mr Rene    3rd  24.0  male         0
1312          Zimmerman, Leo    3rd  29.0  male         0

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1313 entries, 0 to 1312
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      1313 non-null   object
 1   PClass    1312 non-null   object
 2   Age       756 non-null    float64
 3   Sex       1313 non-null   object
 4   Survived  1313 non-null   int64
dtypes: float64(1), int64(1), object(3)
memory usage: 51.4+ KB

In [24]:
df.describe()

              Age     Survived
count  756.000000  1313.000000
mean    30.397989     0.342727
std     14.259049     0.474802
min      0.170000     0.000000
25%     21.000000     0.000000
50%     28.000000     0.000000
75%     39.000000     1.000000
max     71.000000     1.000000

In [26]:
df.isnull().sum()

Name          0
PClass        1
Age         557
Sex           0
Survived      0
dtype: int64

In [28]:
df['PClass'] = df['PClass'].fillna(df['PClass'].mode()[0])
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [30]:
df.isnull().sum()

Name        0
PClass      0
Age         0
Sex         0
Survived    0
dtype: int64

In [32]:
df.describe()

               Age     Survived
count  1313.000000  1313.000000
mean     30.397989     0.342727
std      10.816758     0.474802
min       0.170000     0.000000
25%      26.000000     0.000000
50%      30.397989     0.000000
75%      30.397989     1.000000
max      71.000000     1.000000

In [34]:
df.shape

(1313, 5)

In [36]:
df.size

6565

In [38]:
df.dtypes

Name         object
PClass       object
Age         float64
Sex          object
Survived      int64
dtype: object

In [40]:
df = pd.get_dummies(df, columns=["Sex"], dtype=int)

In [43]:
df.head()

,Name,PClass,Age,Survived,Sex_female,Sex_male
0,"Allen, Miss Elisabeth Walton",1st,29.00,1,1,0
1,"Allison, Miss Helen Loraine",1st,2.00,0,1,0
2,"Allison, Mr Hudson Joshua Creighton",1st,30.00,0,0,1
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,0,1,0
4,"Allison, Master Hudson Trevor",1st,0.92,1,0,1